//! Adversarial stress / throughput integration test for `flux_throughput`.
//!
//! This is a separate crate (an integration test in `tests/`) that exercises the
//! real public API of `flux_throughput` under a hostile, high-volume concurrent
//! load: **hundreds of thousands** of player updates pushed through the
//! [`FluxEngine`] from many producer threads at once, then verified for exact
//! last-write-wins correctness AND measured for raw submit throughput.
//!
//! What it proves:
//!
//! * **Zero lost updates.** With a healthy, zero-latency `MockDb`, a generous
//!   ring and a producer-side retry-on-`Dropped` spin loop, every single update
//!   eventually lands. After a final `flush_now()` + `shutdown()`, the store
//!   holds exactly the per-player MAX version that was ever submitted
//!   (last-write-wins, no lost final update).
//! * **Exact accounting.** `submits_enqueued == total submitted` and
//!   `submits_dropped == 0` (because producers retry until enqueued).
//! * **Throughput.** The whole concurrent submit phase is timed behind a
//!   `Barrier` so all producers start together, and the achieved updates/sec is
//!   printed under `--nocapture`.
//!
//! Determinism: the workload is generated by a fixed integer scheme (no `rand`,
//! no external crates), so the set of (player, version) pairs and the expected
//! per-player final version are fully reproducible. The test is finite and sized
//! to finish well within ~60s in debug (and far faster in `--release`).

use std::collections::HashMap;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Barrier};
use std::time::Instant;

use flux_throughput::{FluxConfig, FluxEngine, PersistenceStore, PlayerId, SubmitOutcome};

// Pull in the concrete in-memory store from the crate's public module surface.
use flux_throughput::store::MockDb;

// ---------------------------------------------------------------------------
// Workload parameters.
//
//   NUM_PRODUCERS  * UPDATES_PER_PRODUCER  == TOTAL_UPDATES
//   8              * 40_000                == 320_000  ( >= 300_000 )
//
// Updates are spread across NUM_PLAYERS == 50_000 distinct ids. With 320_000
// updates that is an average of ~6.4 updates per player, guaranteeing heavy
// coalescing / last-write-wins contention in the cache.
// ---------------------------------------------------------------------------
const NUM_PRODUCERS: usize = 8;
const UPDATES_PER_PRODUCER: usize = 40_000;
const TOTAL_UPDATES: usize = NUM_PRODUCERS * UPDATES_PER_PRODUCER; // 320_000
const NUM_PLAYERS: u64 = 50_000;

/// Ring capacity used by this test (1<<18 = 262_144). Declared here so the
/// producer back-pressure gate can be sized safely below it.
const RING_CAPACITY: usize = 1 << 18;

/// Producer back-pressure high-water mark. While `engine.pending()` (ring +
/// dirty cache) is at/above this, producers spin-wait for the worker to drain.
/// Set far below `RING_CAPACITY` so that even with all producers racing past
/// the gate at once the ring can never actually fill — hence ZERO drop events.
const PENDING_HIGH_WATER: usize = RING_CAPACITY / 2;

/// Per-process, per-call unique temp-dir counter so concurrent / repeated runs
/// never collide on a WAL directory.
static DIR_COUNTER: AtomicUsize = AtomicUsize::new(0);

/// Allocates a unique temp directory for this test's WAL and creates it.
fn unique_wal_dir(name: &str) -> std::path::PathBuf {
    let n = DIR_COUNTER.fetch_add(1, Ordering::Relaxed);
    let dir = std::env::temp_dir().join(format!("flux_{}_{}_{}", name, std::process::id(), n));
    std::fs::create_dir_all(&dir).expect("create unique wal dir");
    dir
}

/// Deterministic workload generator.
///
/// For a given `producer` and step `i` (`0..UPDATES_PER_PRODUCER`) it yields a
/// `(player_id, version)` pair such that, **for any fixed player, the version a
/// single producer submits strictly increases** as `i` grows. We achieve this
/// with a simple integer hashing scheme that is reproducible across runs:
///
///   * `player_id` is a deterministic function of (producer, i) spread over
///     `NUM_PLAYERS` via a large odd stride (full-period walk modulo a power of
///     two-ish space), so each producer touches many players many times.
///   * `version` is monotonically increasing in `i` for that producer, so the
///     k-th time a producer revisits a player it submits a strictly larger
///     version than its previous visit. (Versions are globally unique per
///     producer, hence strictly increasing per (producer, player).)
///
/// Because the cache is last-write-wins **by version**, the final persisted
/// version for a player equals the overall MAX version any producer ever
/// submitted for that player — independent of arrival order.
#[inline]
fn gen_pair(producer: usize, i: usize) -> (PlayerId, u64) {
    // A large odd multiplier gives a well-spread, deterministic player walk.
    // Offsetting by producer decorrelates producers' player sequences so they
    // genuinely contend on overlapping ids.
    let raw = (producer as u64)
        .wrapping_mul(0x9E37_79B9_7F4A_7C15)
        .wrapping_add((i as u64).wrapping_mul(0xC2B2_AE3D_27D4_EB4F));
    let player_id = raw % NUM_PLAYERS;

    // Version strictly increases with `i` for this producer. We add 1 so no
    // version is ever 0 (purely cosmetic / avoids the "unset" sentinel feel).
    let version = (i as u64) + 1;

    (player_id, version)
}

#[test]
fn stress_hundreds_of_thousands_of_concurrent_updates() {
    let wal_dir = unique_wal_dir("stress_concurrency");

    // Generous ring (1<<18 = 262_144) so the worker rarely back-pressures, a
    // large batch (8192) so flushes coalesce aggressively, and a short interval
    // so the worker keeps draining. fsync off: this test measures throughput &
    // correctness of the pipeline, not crash durability (covered elsewhere).
    let config = FluxConfig {
        ring_capacity: RING_CAPACITY,
        flush_max_batch: 8192,
        flush_interval: std::time::Duration::from_millis(5),
        worker_idle_sleep: std::time::Duration::from_millis(1),
        wal_fsync: false,
        store_retry_limit: 5,
        store_retry_backoff: std::time::Duration::from_millis(2),
        ..FluxConfig::default()
    }
    .with_wal_dir(&wal_dir);

    // Healthy, zero-latency in-memory store: no faults, no sleeps — so the only
    // thing that can ever drop a write is a momentarily-full ring, which the
    // producers handle by retrying. Net result must be ZERO drops.
    let db = Arc::new(MockDb::new());
    db.set_healthy(true);

    let engine = Arc::new(
        FluxEngine::start(config, db.clone() as Arc<dyn PersistenceStore>).expect("engine start"),
    );

    // Barrier so all producers begin the timed submit phase simultaneously
    // (NUM_PRODUCERS workers, no extra +1 — we time from the worker side and
    // join them all before stopping the clock).
    let barrier = Arc::new(Barrier::new(NUM_PRODUCERS));

    let phase_start = Instant::now();

    let mut handles = Vec::with_capacity(NUM_PRODUCERS);
    for producer in 0..NUM_PRODUCERS {
        let engine = Arc::clone(&engine);
        let barrier = Arc::clone(&barrier);
        handles.push(std::thread::spawn(move || {
            // Per-producer record of the MAX version it submitted per player.
            // Returned to the main thread to be combined into the global expected
            // final version per player.
            let mut local_max: HashMap<PlayerId, u64> = HashMap::new();

            // All producers rendezvous here, then sprint.
            barrier.wait();

            for i in 0..UPDATES_PER_PRODUCER {
                let (player_id, version) = gen_pair(producer, i);

                // A tiny, distinct payload so the pipeline moves real bytes.
                let blob = version.to_le_bytes().to_vec();

                // Proactive back-pressure gate: before submitting, if the
                // pipeline has too much in flight (ring + dirty cache), spin-wait
                // for the worker to drain it back below a safe high-water mark.
                // This keeps the ring well below capacity so `submit` returns
                // `Enqueued` every time and `submits_dropped` stays exactly 0
                // (the metrics count *every* drop event, including ones a retry
                // loop would otherwise paper over).
                while engine.pending() >= PENDING_HIGH_WATER {
                    std::thread::yield_now();
                }

                // Retry on a full ring so ZERO updates are dropped. With the gate
                // above this loop normally runs exactly once; it remains as a
                // correctness backstop guaranteeing no update is ever abandoned.
                loop {
                    match engine.submit(player_id, version, blob.clone()) {
                        SubmitOutcome::Enqueued => break,
                        SubmitOutcome::Dropped => {
                            // Yield to let the worker drain, then retry the SAME
                            // (player, version) pair — no update is abandoned.
                            std::thread::yield_now();
                        }
                    }
                }

                // Track this producer's max version for the player.
                let e = local_max.entry(player_id).or_insert(0);
                if version > *e {
                    *e = version;
                }
            }

            local_max
        }));
    }

    // Join all producers and fold their per-player maxima into the global
    // expected final version per player (overall MAX across producers).
    let mut expected: HashMap<PlayerId, u64> = HashMap::new();
    for h in handles {
        let local_max = h.join().expect("producer thread panicked");
        for (pid, v) in local_max {
            let e = expected.entry(pid).or_insert(0);
            if v > *e {
                *e = v;
            }
        }
    }

    // Stop the submit-phase clock: every update has been accepted into the ring
    // by now (producers retried until Enqueued).
    let submit_elapsed = phase_start.elapsed();
    let secs = submit_elapsed.as_secs_f64();
    let updates_per_sec = if secs > 0.0 {
        (TOTAL_UPDATES as f64) / secs
    } else {
        f64::INFINITY
    };

    // Drain whatever is still in the ring/cache, then tear the engine down so
    // the worker performs its final flush and the store is fully settled.
    engine.flush_now().expect("flush_now");

    // Capture the metrics snapshot BEFORE `shutdown` consumes the engine. By now
    // every update has been accepted (producers retried until Enqueued), so the
    // submit counters are final.
    let metrics = engine.metrics();

    // Unwrap the Arc so we can consume the engine in shutdown(). All producer
    // threads have joined, so this is the sole owner.
    let engine =
        Arc::try_unwrap(engine).unwrap_or_else(|_| panic!("engine still shared at shutdown"));
    engine.shutdown().expect("shutdown");

    // ----- Correctness assertions ----------------------------------------
    let distinct_players = expected.len();

    // 1) Exactly the distinct players we touched are present in the store.
    assert_eq!(
        db.count(),
        distinct_players,
        "store.count() must equal the number of distinct players touched"
    );

    // 2) For EVERY player, the persisted version is the overall MAX submitted
    //    (last-write-wins; no lost final update). Also verify the blob matches
    //    that final version's payload.
    for (&pid, &exp_ver) in &expected {
        let st = db
            .load(pid)
            .unwrap_or_else(|| panic!("player {pid} missing from store"));
        assert_eq!(
            st.version, exp_ver,
            "player {pid}: stored version {} != expected max {}",
            st.version, exp_ver
        );
        assert_eq!(
            st.blob,
            exp_ver.to_le_bytes().to_vec(),
            "player {pid}: stored blob does not match final version payload"
        );
    }

    // 3) Metrics accounting: every submit was enqueued exactly once, and the
    //    producer retry loop means NOTHING was permanently dropped.
    assert_eq!(
        metrics.submits_enqueued, TOTAL_UPDATES as u64,
        "submits_enqueued must equal the total number of updates submitted"
    );
    assert_eq!(
        metrics.submits_dropped, 0,
        "submits_dropped must be 0 (producers retry on a full ring)"
    );

    // ----- Throughput + metrics report (visible with --nocapture) --------
    println!("================ FluxThroughput stress report ================");
    println!("producers              : {NUM_PRODUCERS}");
    println!("updates / producer     : {UPDATES_PER_PRODUCER}");
    println!("total updates submitted: {TOTAL_UPDATES}");
    println!("distinct players       : {distinct_players}");
    println!(
        "submit phase elapsed   : {:.3} s",
        submit_elapsed.as_secs_f64()
    );
    println!("throughput             : {updates_per_sec:.0} updates/sec");
    println!("--- final engine metrics ---");
    println!("submits_enqueued       : {}", metrics.submits_enqueued);
    println!("submits_dropped        : {}", metrics.submits_dropped);
    println!("max_submit_nanos       : {}", metrics.max_submit_nanos);
    println!("avg_submit_nanos       : {:.1}", metrics.avg_submit_nanos());
    println!("flushes                : {}", metrics.flushes);
    println!("records_flushed        : {}", metrics.records_flushed);
    println!("max_flush_nanos        : {}", metrics.max_flush_nanos);
    println!("wal_appends            : {}", metrics.wal_appends);
    println!("wal_records            : {}", metrics.wal_records);
    println!("store_errors           : {}", metrics.store_errors);
    println!("store_retries          : {}", metrics.store_retries);
    println!("==============================================================");

    // Clean up the unique temp WAL directory.
    let _ = std::fs::remove_dir_all(&wal_dir);
}
